import Head from "next/head";
import Image from "next/image";
import Table from "../components/table";
import Button from "../components/Button";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch(`https://jsonplaceholder.typicode.com/comments`)
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((err) => console.log(err));
  }, []);

  const column = [
    {
      name: "No",
      width: "50px",
      renderValue: (_, index) => <div>{index + 1}</div>,
    },
    {
      name: "Name",
      width: "200px",
      renderValue: (item) => <div className="pr-4">{item.name}</div>,
    },
    {
      name: "Email",
      width: "150px",
      renderValue: (item) => item.email,
    },
    {
      name: "Comment",
      width: "400px",
      renderValue: (item) => item.body,
    },
  ];

  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="dark">Oke</Button>

      <div className=" mx-auto">
        <Table
          column={column}
          data={data}
          rowOnclicked={(e, i) => console.log(e)}
          highlightOnHover
          loading={false}
          PageSize={10}
        />
      </div>
    </div>
  );
}
